type Pair = [string,string];
type ServiceDetailData = {slug:string; title:string; desc:string; heroA:string; heroB:string; eyebrow:string; introTitle:string; image:string; capabilities:string[]; introParagraphs?:string[]; miniFacts?:string[]; capabilityDescriptions?:string[]; gains?:Pair[]; process?:Pair[]; scopeIntro?:string; gainsIntro?:string; processIntro?:string; systemEyebrow?:string; systemTitle?:string; systemEm?:string; systemText?:string; trustEyebrow?:string; trustTitle?:string; trustIntro?:string; trustItems?:Pair[]; ctaTitle?:string};

export default function ServiceDetailTemplate({d}:{d:ServiceDetailData}) {
 const wa=`https://wa.me/905416653499?text=${encodeURIComponent(`Merhaba, ${d.title} hizmetiniz hakkında bilgi almak istiyorum.`)}`;
 const gains=d.gains || [["Zaman ve Verimlilik","Süreci sadeleştirir, gereksiz adımları azaltır ve günlük kullanımı hızlandırır."],["Güvenilir Yapı","İhtiyacın kritik noktalarını kontrollü ve sürdürülebilir bir yapıda ele alır."],["Net Kontrol","Sistemin ne yaptığını, nerede olduğunu ve nasıl gelişeceğini görünür hale getirir."],["Büyümeye Uyum","İhtiyaç değiştikçe yeni özellikler ve bağlantılarla geliştirilebilir."],["Uzun Vadeli Değer","Kısa vadeli bir çözüm yerine işletmenize hizmet eden kalıcı bir dijital yapı hedeflenir."]];
 const process=d.process || [["İhtiyacı Anlıyoruz","Hedefinizi, mevcut yapıyı ve gerçek problemi netleştiriyoruz."],["Planlıyoruz","Doğru kapsamı, mimariyi ve uygulama yolunu belirliyoruz."],["Tasarlıyoruz","Kullanıcı ve iş akışını sade, anlaşılır bir deneyime dönüştürüyoruz."],["Uyguluyoruz","Planlanan çözümü güvenli ve sürdürülebilir biçimde hayata geçiriyoruz."],["Test Ediyoruz","Kritik akışları, performansı ve kullanım senaryolarını kontrol ediyoruz."],["Yayına Alıyoruz","Son kontrolleri tamamlayıp çözümü gerçek kullanım ortamına taşıyoruz."],["Geliştiriyoruz","Yeni ihtiyaçlar oluştuğunda mevcut yapıyı kontrollü biçimde büyütüyoruz."]];
 return <main className="serviceDetailPage serviceDetailRefined">
  <header className="detailNav"><nav><a href="/#anasayfa">Anasayfa</a><a href="/#ahc-kimdir">AHC Kimdir?</a><a href="/#hizmetler">Hizmetler</a><a href="/#projeler">Tamamlanan Projeler</a><a href="/#iletisim">İletişim</a></nav></header>
  <section className="detailHero detailHeroTextOnly"><div className="detailHeroGlow detailHeroGlowA"/><div className="detailHeroGlow detailHeroGlowB"/><div className="detailHeroCode" aria-hidden="true"><span>const experience = design(requirements);</span><span>architecture.scale(&quot;with-your-business&quot;);</span><span>secure.connect(data, users);</span><span>{'deploy({ quality: "production" });'}</span><span>while (needs.change) product.evolve();</span></div><div className="detailHeroCopy"><span className="detailEyebrow">{d.title.toLocaleUpperCase('tr-TR')}</span><h1>{d.heroA}<br/><em>{d.heroB}</em></h1><p>{d.desc}</p><div className="detailHeroPrinciples"><span><i/> İhtiyaca özel yaklaşım</span><span><i/> Güvenli altyapı</span><span><i/> Ölçeklenebilir yapı</span><span><i/> Sürdürülebilir çözüm</span></div></div></section>
  <section className="detailIntro detailSection"><div className="detailSectionTitle"><span>{d.eyebrow}</span><h2>{d.introTitle.split(' nedir?')[0]}<br/><em>nedir?</em></h2></div><div className="detailReadingCard">{(d.introParagraphs || [`${d.title}, ihtiyacınızı hazır kalıplara sıkıştırmadan hedefinize göre planlanan profesyonel bir hizmettir.`,"Önce mevcut durumu ve beklentinizi anlıyor; ardından kullanıcı, teknik yapı, güvenlik, performans ve sürdürülebilirlik ihtiyaçlarını birlikte değerlendiriyoruz.","Amacımız yalnızca işi tamamlamak değil, günlük kullanımda anlaşılır, güvenilir ve gerektiğinde geliştirilebilir bir sonuç ortaya çıkarmaktır."]).map((p,i)=>i===0?<p key={p} className="detailLead">{p}</p>:<p key={p}>{p}</p>)}<div className="detailMiniFacts">{(d.miniFacts || ["İhtiyaca tam uyum","Gereksiz karmaşa yok","Geliştirilebilir yapı","Profesyonel uygulama"]).map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="detailCapabilities detailSection detailSectionStacked"><div className="detailCenteredTitle"><span>HİZMET KAPSAMI</span><h2>Neleri ele alıyoruz?</h2><p>{d.scopeIntro || "Hizmetin kapsamını ihtiyacınıza göre belirliyor, gerekli parçaları tek bir bütün olarak planlıyoruz."}</p></div><div className="capabilityGrid capabilityGridClean">{d.capabilities.map((x,i)=><article key={x}><h3>{x}</h3><p>{(d.capabilityDescriptions || ['İhtiyacınıza göre planlanan ve ana çözümle birlikte çalışan profesyonel yapı.','Kullanım kolaylığı, güvenilirlik ve sürdürülebilirlik odağında ele alınır.','Mevcut sisteminiz ve hedeflerinizle uyumlu olacak şekilde şekillendirilir.'])[i % (d.capabilityDescriptions?.length || 3)]}</p></article>)}</div></section>
  <section className="detailGains detailSection detailSectionStacked"><div className="detailCenteredTitle"><span>İŞLETMEYE KATKISI</span><h2>Size ne kazandırır?</h2><p>{d.gainsIntro || "Teknik ayrıntılardan önce, hizmetin günlük işinize ve dijital yapınıza sağlayacağı değere odaklanıyoruz."}</p></div><div className="gainRail gainRailClean">{gains.map(([a,b])=><article key={a}><div className="gainGlyph" aria-hidden="true"><i/></div><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="detailProcess detailSection detailSectionStacked"><div className="detailCenteredTitle"><span>ÇALIŞMA SÜRECİ</span><h2>Nasıl hayata geçiriyoruz?</h2><p>{d.processIntro || "Her aşamayı anlaşılır tutuyor, ne yaptığımızı ve neden yaptığımızı görünür kılıyoruz."}</p></div><div className="detailTimeline detailTimelineClean"><div className="detailTimelineLine"/>{process.map(([a,b])=><article key={a}><div className="detailTimelineNode"><span/></div><div><h3>{a}</h3><p>{b}</p></div></article>)}</div></section>
  <section className="detailSystem detailSection detailSystemRefined"><div className="detailSectionTitle systemCopy"><span>{d.systemEyebrow || "BÜTÜNSEL YAKLAŞIM"}</span><h2>{d.systemTitle || "Tek bir parça değil."}<br/><em>{d.systemEm || "Tam bir çözüm."}</em></h2><p>{d.systemText || `${d.title} hizmetini yalnızca görünen sonuç üzerinden değil; kullanıcı, altyapı, güvenlik, performans ve sürdürülebilirlik parçalarıyla birlikte ele alıyoruz.`}</p></div><div className="systemVisualLive" aria-label={`${d.title} görseli`}><img src={d.image} alt={`${d.title} profesyonel hizmet görseli`}/><div className="systemVisualGlow" aria-hidden="true"/><div className="systemVisualScan" aria-hidden="true"/><span className="systemVisualSpark sparkOne"/><span className="systemVisualSpark sparkTwo"/><span className="systemVisualSpark sparkThree"/></div></section>
  <section className="detailTrust detailSection detailSectionStacked"><div className="detailCenteredTitle compactTitle"><span>{d.trustEyebrow || "SÜREKLİLİK"}</span><h2>{d.trustTitle || "Bugün için doğru. Yarın için geliştirilebilir."}</h2><p>{d.trustIntro || "Çözümü tek seferlik bir teslim olarak değil, ihtiyaç oldukça gelişebilecek sağlam bir yapı olarak ele alıyoruz."}</p></div><div className="trustStrip">{(d.trustItems || [["Güvenlik","Kritik noktalar ve veri erişimi çözümün doğal bir parçası olarak değerlendirilir."],["Uyumluluk","Mevcut yapınız ve gerekli üçüncü taraf servislerle kontrollü biçimde çalışabilir."],["Performans","Gerçek kullanım koşullarında hızlı ve kararlı bir deneyim hedeflenir."],["Bakım & Geliştirme","Yeni ihtiyaçlarda mevcut yapı kontrollü biçimde genişletilebilir."]]).map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="detailFinalCta"><div><span>İLETİŞİM</span><h2>{d.ctaTitle || `${d.title} hakkında konuşalım.`}</h2><p>Sorularınız, projeniz hakkında görüşmek, teklif almak veya fiyat bilgisi için aşağıdaki butondan WhatsApp üzerinden bizimle iletişime geçebilirsiniz.</p></div><a href={wa} target="_blank" rel="noreferrer" className="detailWhatsapp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3.2A12.4 12.4 0 0 0 5.4 22l-1.7 6.3 6.4-1.7A12.4 12.4 0 1 0 16 3.2Zm0 22.4c-2 0-3.9-.6-5.5-1.6l-.4-.2-3.8 1 1-3.7-.3-.4A10 10 0 1 1 16 25.6Z"/></svg>WhatsApp’tan İletişime Geç <b>→</b></a></section>
 </main>
}
